language: python
python:
  - "3.4"
# command to install dependencies
<<<<<<< HEAD
install:
  - pip install regex
  - pip install -r requirements-dev.txt

=======
install: 
  - pip install -r requirements-dev.txt
  - pip install regex 
>>>>>>> 755e737fe6576ae097ee94b16ae03072a4210bf7
# command to run tests
script: 
  - nosetests tests
  - flake8 dqc_us_rules tests
  - travis_wait 45 ./run_integration.sh
